import OpenAI from "openai";

function getHoroscope(sign) {
  return sign;
}

const MODEL = "arcee-ai/trinity-large-preview:free";

const client = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: process.env.OPENROUTER_API_KEY,
});

const functionCall = async () => {
  const tools = [
    {
      type: "function" as const,
      strict: true,
      name: "get_horoscope",
      description: "Get today's horoscope for an astrological sign.",
      parameters: {
        type: "object" as const,
        properties: {
          sign: {
            type: "string",
            description: "An astrological sign like Taurus or Aquarius",
          },
        },
        required: ["sign"],
        additionalProperties: false,
      },
    },
  ];

  let input: any = [
    { role: "user" as const, content: "What is my horoscope? I am an Pisces." },
  ];

  let response = await client.responses.create({
    model: MODEL,
    tools,
    input,
  });

  console.log(JSON.stringify(response, null, 2));

  response.output.forEach((item) => {
    if (item.type == "function_call") {
      if (item.name == "get_horoscope") {
        // 3. Execute the function logic for get_horoscope
        const horoscope = getHoroscope(JSON.parse(item.arguments));

        // 4. Provide function call results to the model
        input.push({
          type: "function_call_output" as const,
          call_id: item.call_id,
          output: JSON.stringify({
            horoscope,
          }),
        });
      }
    }
  });

  console.log("Final input:");
  console.log(JSON.stringify(input, null, 2));

  response = await client.responses.create({
    model: MODEL,
    instructions: "Respond only with a horoscope generated by a tool.",
    tools,
    input,
  });

  // 5. The model should be able to give a response!
  console.log("Final output:");
  console.log(JSON.stringify(response.output, null, 2));
};

async function functionCallWithStreaming() {
  const tools = [
    {
      type: "function" as const,
      name: "get_weather",
      description:
        "Get current temperature for provided coordinates in celsius.",
      parameters: {
        type: "object" as const,
        properties: {
          latitude: { type: "number" },
          longitude: { type: "number" },
        },
        required: ["latitude", "longitude"],
        additionalProperties: false,
      },
      strict: true,
    },
  ];

  const stream = await client.responses.create({
    model: MODEL,
    input: [
      { role: "user", content: "What's the weather like in Paris today?" },
    ],
    tools,
    stream: true,
  });

  console.log(stream);

  for await (const event of stream) {
    console.log(JSON.stringify(event, null, 2));
  }
}

const customToolCall = async () => {
  const response = await client.responses.create({
    model: MODEL,
    input: "Use the code_exec tool to print hello world to the console.",
    tools: [
      {
        type: "function" as const,
        name: "code_exec",
        description: "Executes arbitrary Python code.",
        strict: false,
        parameters: {
          type: "object" as const,
          properties: {
            code: {
              type: "string",
              description: "The Python code to execute",
            },
          },
          required: ["code"],
        },
      },
    ],
  });

  console.log(response.output);
};

async function main() {
  customToolCall();
}

main().catch(console.error);
